### ISSUE TITLE
Questions about the scope of this wonderful library...

### ISSUE THREAD

**Issue by richlysakowski** [klahnakoski/pyLibrary#4]
I know this is supposed to be for reporting issues, but I have questions of scoping and application of this library that the read.me does not answer for me.  

This is a great library that does many cool things.  I too spend an inordinate amount of time instrumenting my code and creating my own "utils" library so that I don't have to do this repeatedly for my projects.  pyLibrary appears to correct problems to make Python 2.7 more consistent across platforms and bring it up to date with expectations for functional and OO programming on Windows and other platforms.   There are no examples of usage.  QUESTION:  Do can you provide some pointers to your application package that show how you use these various utils packages? 

QUESTION: I only use 64-bit Python right now; many of these modules seem aimed at 32-bit Python.  Is that true?   Why 32-bit in 2023?   For modern 32-bit portable devices and microcontrollers or very old VMs running Python 2.7 on Windows XP 32.bit? 

QUESTION: Is this still primarily targeted at Python 2.7?   It was updated as little as 7 months ago, in 2023.  Without diving into the code too far, it has subpackages and modules for MANY aspects of Python usage (files, internet, parsing, sql, threads, etc.)  

It also has the moz_sql_parser, which led me to your github repos the first place.  I thought moz_sql_parser was updated and replaced by the mo_sql_parser package.  

QUESTION: Are all the "mo_***" packages historically related to Mozilla browser work, or just "More..." ( "Mo...Better!" ) Python ?  

[mo_auth](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_auth)
[mo_collections](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_collections)
[mo_dots](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_dots)
[mo_fabric](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_fabric)
[mo_files](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_files)
[mo_future](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_future)
[mo_graphs](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_graphs)
[mo_hg](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_hg)
[mo_http](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_http)
[mo_imports](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_imports)
[mo_json](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_json)
[mo_json_config](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_json_config)
[mo_kwargs](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_kwargs)
[mo_logs](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_logs)
[mo_math](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_math)
[mo_parquet](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_parquet)
[mo_parsing](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_parsing)
[mo_sql](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_sql)
[mo_streams](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_streams)
[mo_testing](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_testing)
[mo_threads](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_threads)
[mo_times](https://github.com/klahnakoski/pyLibrary/tree/dev/mo_times)
[moz_sql_parser](https://github.com/klahnakoski/pyLibrary/tree/dev/moz_sql_parser)

**Comment by klahnakoski** [comment]
This library started as utils library around 2013, and started to breakup into packages ("children", if you will) around 2017.  The [pyLibrary subdirectory](https://github.com/klahnakoski/pyLibrary/tree/dev/pyLibrary) is all that remains; I have never made a package for it.  It lingers only to provide support for other packages.

This repo (not including the pyLibrary subdirectory) serves to synchronize the packages that have split off from this: These children still work tightly together, and sometimes all-the-code gets synchronized here for global name changes and other automated refactorings before being sent back to own repos.   The updates you are seeing is me doing this type of synchronization.


> show how you use these various utils packages?

* The primary driver for these packages was [ActiveData](https://github.com/mozilla/ActiveData) and [BugzillaETL](https://github.com/mozilla/Bugzilla-ETL), which are probably not in use anymore
* [My repos](https://github.com/klahnakoski?tab=repositories) all use one or more of these packages

> many of these modules seem aimed at 32-bit Python. Is that true?

32bit was only relevant up to 2019, when the last of the legacy 2.7 code was migrated to 3.x

>Is this still primarily targeted at Python 2.7? 

No.  Maybe I will update the README to say this.

> I thought moz_sql_parser was updated and replaced by the mo_sql_parser package.

yes, mo-sql-parsing is the replacement.  I have not maintained this repo well enough to keep the names updated too 

> QUESTION: Are all the "mo_***" packages historically related to Mozilla browser work, or just "More..." ( "Mo...Better!" ) Python ?

These packages were built while supporting Mozilla's automated tools team:  Their job was to run the builds and tests for the browser developers.  None of this code will be found in the browser.
